### ISSUE TITLE
Using "blastx" with annotate

### ISSUE THREAD

**Issue by gopel** [Bioconductor/annotate#1]
Hi,

  I am currently working on an R pipeline using "annotate" (which is part of the bioconductor package). First, I want to thank you for this excellent tool. It is really useful for me.
  I also have a question about future development please. Right now, the function blastSequences only works for "blastn", would it be possible to make it available for other programs (like "blastx") please?

  Thanks in advance.

  Best regards,

  Yanis

**Comment by mtmorgan** [comment]
Unfortunately we don't have resources to develop annotate in this way, but would of course welcome a pull request. Since we can't act on this in the near term, I'll close the issue.
