### ISSUE TITLE
Question about blastSequences

### ISSUE THREAD

**Issue by NeginValizadegan** [Bioconductor/annotate#2]
Hello all,

I run blastSequences on a fasta file and get a data frame but I am having trouble writing it appropriately to a csv or txt file. The ||| in the file I think might be distorting thing. In general, how do I write the results out in a file?

**Comment by lshep** [comment]
Please ask these types of questions on the [support.bioconductor.org](https://support.bioconductor.org/)  help site.  That way other users that may have more experience working with these types of objects could also chime in.  It would also be helpful when posting there what you mean by trouble writing it appropriately as using example code from the package the following wrote to a file without ERROR
```
temp = blastSequences(x = "GGCCTTCATTTACCCAAAATG", as="data.frame")
write.csv(temp, file = tempfile())
```
Cheers!
